/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 f35.gltf 
Author: bohmerang (https://sketchfab.com/bohmerang)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/f-35-lightning-ii-fighter-jet-free-b1ab1c0090e34b0fbfe667e706023e6d
Title: F-35 Lightning II - Fighter Jet - Free
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/f35.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['F-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.glass} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['F-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['inst-glass']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['inst-glass']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['F-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['F-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['F-35-landingLights']} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/f35.gltf')
